networks:
  caddy_net:
    external: true

services:
  caddy:
    build: ./caddy_global
    container_name: caddy
    restart: unless-stopped
    environment:
      VPN_ADMIN_SERVER_ADDRESS: ${VPN_ADMIN_SERVER_ADDRESS:-}
      CF_API_TOKEN: ${CF_API_TOKEN:-}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./caddy_global/Caddyfile:/etc/caddy/Caddyfile
      - caddy_root_data:/data
      - caddy_root_config:/config
    networks:
      - caddy_net

volumes:
  caddy_root_data:
  caddy_root_config: