services:
  tailscale_web:
    image: tailscale/tailscale:latest
    restart: on-failure
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_AUTH_ONCE=true
      - TS_ROUTES=${TS_ROUTES:-172.21.0.0/16,172.23.0.0/16}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
       - ${BASE_DATA_PATH:-./data}/tailscale:/var/lib/tailscale
    container_name: tailscale_web
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true